services:
   wrestling-crawler:
       image: wrestling-crawler
       container_name: wrestling-crawler

       build:
         context: .
         dockerfile: Dockerfile

       volumes:
         - ${PWD}/../data/referees:/app/referees
